source 'https://rubygems.org'
gem 'sinatra'
gem 'sinatra-reloader'
gem 'sinatra-cross_origin'
gem 'json', '~> 2.6'
gem 'httparty'
gem 'http', '~> 3.0'
gem 'rest-client', '~> 1.8'
gem 'gtfs-realtime-bindings', '~> 0.0.5'
gem 'uri'
gem 'google-protobuf', '~> 3.19', '>= 3.19.1'
